#telem channels
PACK_1_VOLTAGE_NAME = 'P1_V'
PACK_2_VOLTAGE_NAME = 'P2_V'
PACK_3_VOLTAGE_NAME = 'P3_V'
PACK_4_VOLTAGE_NAME = 'P4_V'

PACK_1_CURRENT_NAME = 'P1_A'
PACK_2_CURRENT_NAME = 'P2_A'
PACK_3_CURRENT_NAME = 'P3_A'
PACK_4_CURRENT_NAME = 'P4_A'

PACK_1_COMMS_NAME = 'P1_COM'
PACK_2_COMMS_NAME = 'P2_COM'
PACK_3_COMMS_NAME = 'P3_COM'
PACK_4_COMMS_NAME = 'P4_COM'

FU_PUMP_ESC_BUS_VOLT_NAME = 'FUP_BUS_V'
OX_PUMP_ESC_BUS_VOLT_NAME = 'OXP_BUS_V'

FU_PUMP_ESC_CURRENT_NAME = 'FUP_CURR'
OX_PUMP_ESC_CURRENT_NAME = 'OXP_CURR'

FU_PUMP_RPM_NAME = 'FUP_RPM'
OX_PUMP_RPM_NAME = 'FUP_RPM'

#command channels
PACK_1_DISCONNECT_NAME = 'P1_DISCONN'
PACK_2_DISCONNECT_NAME = 'P2_DISCONN'
PACK_3_DISCONNECT_NAME = 'P3_DISCONN'
PACK_4_DISCONNECT_NAME = 'P4_DISCONN'

FU_PUMP_ESC_ENABLE_NAME = 'FUP_ESC_EN'
OX_PUMP_ESC_ENABLE_NAME = 'OXP_ESC_EN'

FU_PUMP_RPM_SETPOINT_NAME = 'FUP_RPM_SP'
OX_PUMP_RPM_SETPOINT_NAME = 'OXP_RPM_SP'
